# -*- coding: utf-8 -*-
"""Snapshot generado de ubicaciones oficiales derivadas del DBF."""

from __future__ import annotations

from typing import Final

CATALOG_GENERATED_AT: Final[str] = '2026-04-27'
CATALOG_SOURCES: Final[dict[str, str]] = {'CATALOGO_NACIONAL_DE_ESTACIONES_(EXCEL).xls': 'CNE_IDEAM.xls', 'CATALOGO_NACIONAL_DE_OTRAS_ENTIDADES_(EXCEL).xls': 'CNE_OE.xls', 'CATALOGO_NACIONAL_DE_ESTACIONES_(SHAPE).dbf': 'CNE_IDEAM_Final.dbf'}

OFFICIAL_LOCATIONS: Final[tuple[tuple[str, str], ...]] = (
    ('Amazonas', 'El Encanto'),
    ('Amazonas', 'La Chorrera'),
    ('Amazonas', 'La Pedrera'),
    ('Amazonas', 'Leticia'),
    ('Amazonas', 'Mirití-Paraná (Campoamor)'),
    ('Amazonas', 'Puerto Alegría'),
    ('Amazonas', 'Puerto Arica'),
    ('Amazonas', 'Puerto Nariño'),
    ('Amazonas', 'Santander (Araracuara)'),
    ('Amazonas', 'Tarapacá'),
    ('Antioquia', 'Abejorral'),
    ('Antioquia', 'Abriaquí'),
    ('Antioquia', 'Alejandría'),
    ('Antioquia', 'Amalfi'),
    ('Antioquia', 'Andes'),
    ('Antioquia', 'Angostura'),
    ('Antioquia', 'Anorí'),
    ('Antioquia', 'Anzá'),
    ('Antioquia', 'Apartadó'),
    ('Antioquia', 'Arboletes'),
    ('Antioquia', 'Argelia (Antioquia)'),
    ('Antioquia', 'Armenia (Antioquia)'),
    ('Antioquia', 'Barbosa (Antioquia)'),
    ('Antioquia', 'Bello'),
    ('Antioquia', 'Belmira'),
    ('Antioquia', 'Betania'),
    ('Antioquia', 'Betulia (Antioquia)'),
    ('Antioquia', 'Briceño (Antioquia)'),
    ('Antioquia', 'Buriticá'),
    ('Antioquia', 'Caicedo'),
    ('Antioquia', 'Caldas (Antioquia)'),
    ('Antioquia', 'Campamento'),
    ('Antioquia', 'Caramanta'),
    ('Antioquia', 'Carepa'),
    ('Antioquia', 'Carmen De Viboral'),
    ('Antioquia', 'Caucasia'),
    ('Antioquia', 'Cañasgordas'),
    ('Antioquia', 'Chigorodó'),
    ('Antioquia', 'Ciudad Bolívar'),
    ('Antioquia', 'Cocorná'),
    ('Antioquia', 'Concepción (Antioquia)'),
    ('Antioquia', 'Concordia (Antioquia)'),
    ('Antioquia', 'Cáceres'),
    ('Antioquia', 'Dabeiba'),
    ('Antioquia', 'Don Matías'),
    ('Antioquia', 'El Bagre'),
    ('Antioquia', 'Entrerrios'),
    ('Antioquia', 'Fredonia'),
    ('Antioquia', 'Frontino'),
    ('Antioquia', 'Giraldo'),
    ('Antioquia', 'Girardota'),
    ('Antioquia', 'Granada (Antioquia)'),
    ('Antioquia', 'Guarne'),
    ('Antioquia', 'Gómez Plata'),
    ('Antioquia', 'Heliconia'),
    ('Antioquia', 'Ituango'),
    ('Antioquia', 'Jardín'),
    ('Antioquia', 'Jericó (Antioquia)'),
    ('Antioquia', 'La Ceja'),
    ('Antioquia', 'La Pintada'),
    ('Antioquia', 'La Unión (Antioquia)'),
    ('Antioquia', 'Liborina'),
    ('Antioquia', 'Marinilla'),
    ('Antioquia', 'Medellín'),
    ('Antioquia', 'Montebello'),
    ('Antioquia', 'Murindó'),
    ('Antioquia', 'Mutatá'),
    ('Antioquia', 'Nechí'),
    ('Antioquia', 'Necoclí'),
    ('Antioquia', 'Olaya'),
    ('Antioquia', 'Peque'),
    ('Antioquia', 'Peñol'),
    ('Antioquia', 'Pueblorrico'),
    ('Antioquia', 'Puerto Berrío'),
    ('Antioquia', 'Puerto Nare'),
    ('Antioquia', 'Puerto Triunfo'),
    ('Antioquia', 'Remedios'),
    ('Antioquia', 'Retiro'),
    ('Antioquia', 'Rionegro (Antioquia)'),
    ('Antioquia', 'Sabanalarga (Antioquia)'),
    ('Antioquia', 'Salgar'),
    ('Antioquia', 'San Andrés (Antioquia)'),
    ('Antioquia', 'San Carlos (Antioquia)'),
    ('Antioquia', 'San Francisco (Antioquia)'),
    ('Antioquia', 'San Jerónimo'),
    ('Antioquia', 'San José De La Montaña'),
    ('Antioquia', 'San Juan De Urabá'),
    ('Antioquia', 'San Luis (Antioquia)'),
    ('Antioquia', 'San Pedro De Urabá'),
    ('Antioquia', 'San Rafael'),
    ('Antioquia', 'San Roque'),
    ('Antioquia', 'San Vicente'),
    ('Antioquia', 'Santa Bárbara (Antioquia)'),
    ('Antioquia', 'Santa Fe De Antioquia'),
    ('Antioquia', 'Santa Rosa De Osos'),
    ('Antioquia', 'Santo Domingo'),
    ('Antioquia', 'Santuario (Antioquia)'),
    ('Antioquia', 'Segovia'),
    ('Antioquia', 'Sonsón'),
    ('Antioquia', 'Sopetrán'),
    ('Antioquia', 'Tarazá'),
    ('Antioquia', 'Titiribí'),
    ('Antioquia', 'Toledo (Antioquia)'),
    ('Antioquia', 'Turbo'),
    ('Antioquia', 'Támesis'),
    ('Antioquia', 'Uramita'),
    ('Antioquia', 'Urrao'),
    ('Antioquia', 'Valdivia'),
    ('Antioquia', 'Valparaiso'),
    ('Antioquia', 'Vegachí'),
    ('Antioquia', 'Venecia (Antioquia)'),
    ('Antioquia', 'Vigia Del Fuerte'),
    ('Antioquia', 'Yalí'),
    ('Antioquia', 'Yarumal'),
    ('Antioquia', 'Yolombó'),
    ('Antioquia', 'Yondó (Casabe)'),
    ('Antioquia', 'Zaragoza'),
    ('Arauca', 'Arauca'),
    ('Arauca', 'Arauquita'),
    ('Arauca', 'Cravo Norte'),
    ('Arauca', 'Saravena'),
    ('Arauca', 'Tame'),
    ('Archipiélago de San Andres, Providencia y Santa Catalina', 'San Andres Y  Providencia (Santa Isabel)'),
    ('Archipiélago de San Andres, Providencia y Santa Catalina', 'San Andrés (Archipiélago de San Andrés, Providencia y Santa Catalina)'),
    ('Atlantico', 'Baranoa'),
    ('Atlantico', 'Barranquilla'),
    ('Atlantico', 'Campo De La Cruz'),
    ('Atlantico', 'Candelaria (Atlántico)'),
    ('Atlantico', 'Juan De Acosta'),
    ('Atlantico', 'Luruaco'),
    ('Atlantico', 'Manatí'),
    ('Atlantico', 'Piojó'),
    ('Atlantico', 'Polonuevo'),
    ('Atlantico', 'Ponedera'),
    ('Atlantico', 'Puerto Colombia (Atlántico)'),
    ('Atlantico', 'Repelón'),
    ('Atlantico', 'Sabanagrande'),
    ('Atlantico', 'Sabanalarga (Atlántico)'),
    ('Atlantico', 'Santa Lucia'),
    ('Atlantico', 'Soledad'),
    ('Atlantico', 'Suan'),
    ('Atlantico', 'Tubará'),
    ('Atlantico', 'Usiacurí'),
    ('Bogotá', 'Bogota, D.C'),
    ('Bolívar', 'Achí'),
    ('Bolívar', 'Altos Del Rosario'),
    ('Bolívar', 'Arenal'),
    ('Bolívar', 'Arjona'),
    ('Bolívar', 'Arroyohondo'),
    ('Bolívar', 'Barranco De Loba'),
    ('Bolívar', 'Calamar (Bolívar)'),
    ('Bolívar', 'Cantagallo'),
    ('Bolívar', 'Cartagena De Indias'),
    ('Bolívar', 'Cicuco'),
    ('Bolívar', 'Córdoba (Bolívar)'),
    ('Bolívar', 'El Carmén De Bolívar'),
    ('Bolívar', 'El Guamo'),
    ('Bolívar', 'El Peñón (Bolívar)'),
    ('Bolívar', 'Hatillo De Loba'),
    ('Bolívar', 'Magangué'),
    ('Bolívar', 'Mahates'),
    ('Bolívar', 'Margarita'),
    ('Bolívar', 'María La Baja'),
    ('Bolívar', 'Mompós'),
    ('Bolívar', 'Montecristo'),
    ('Bolívar', 'Morales (Bolívar)'),
    ('Bolívar', 'Pinillos'),
    ('Bolívar', 'Regidor'),
    ('Bolívar', 'Ríoviejo'),
    ('Bolívar', 'San Cristóbal'),
    ('Bolívar', 'San Estanislao'),
    ('Bolívar', 'San Fernando'),
    ('Bolívar', 'San Jacinto'),
    ('Bolívar', 'San Jacinto Del Cauca'),
    ('Bolívar', 'San Juan Nepomuceno'),
    ('Bolívar', 'San Martín De Loba'),
    ('Bolívar', 'San Pablo (Bolívar)'),
    ('Bolívar', 'Santa Catalina'),
    ('Bolívar', 'Santa Rosa Del Sur'),
    ('Bolívar', 'Simití'),
    ('Bolívar', 'Talaigua Nuevo'),
    ('Bolívar', 'Tiquisio (Puerto Rico)'),
    ('Bolívar', 'Turbaco'),
    ('Bolívar', 'Zambrano'),
    ('Boyacá', 'Almeida'),
    ('Boyacá', 'Aquitania'),
    ('Boyacá', 'Arcabuco'),
    ('Boyacá', 'Belén (Boyacá)'),
    ('Boyacá', 'Berbeo'),
    ('Boyacá', 'Betéitiva'),
    ('Boyacá', 'Boavita'),
    ('Boyacá', 'Boyacá'),
    ('Boyacá', 'Buenavista (Boyacá)'),
    ('Boyacá', 'Campohermoso'),
    ('Boyacá', 'Cerinza'),
    ('Boyacá', 'Chinavita'),
    ('Boyacá', 'Chiquinquirá'),
    ('Boyacá', 'Chiscas'),
    ('Boyacá', 'Chita'),
    ('Boyacá', 'Chivatá'),
    ('Boyacá', 'Chivor'),
    ('Boyacá', 'Chíquiza'),
    ('Boyacá', 'Coper'),
    ('Boyacá', 'Corrales'),
    ('Boyacá', 'Covarachía'),
    ('Boyacá', 'Cubará'),
    ('Boyacá', 'Cuítiva'),
    ('Boyacá', 'Cómbita'),
    ('Boyacá', 'Duitama'),
    ('Boyacá', 'El Cocuy'),
    ('Boyacá', 'El Espino'),
    ('Boyacá', 'Firavitoba'),
    ('Boyacá', 'Gachantivá'),
    ('Boyacá', 'Garagoa'),
    ('Boyacá', 'Guacamayas'),
    ('Boyacá', 'Guayatá'),
    ('Boyacá', 'Guicán'),
    ('Boyacá', 'Gámeza'),
    ('Boyacá', 'Iza'),
    ('Boyacá', 'Jenesano'),
    ('Boyacá', 'Jericó (Boyacá)'),
    ('Boyacá', 'La Capilla'),
    ('Boyacá', 'La Uvita'),
    ('Boyacá', 'Labranzagrande'),
    ('Boyacá', 'Macanal'),
    ('Boyacá', 'Maripí'),
    ('Boyacá', 'Miraflores (Boyacá)'),
    ('Boyacá', 'Mongua'),
    ('Boyacá', 'Monguí'),
    ('Boyacá', 'Moniquirá'),
    ('Boyacá', 'Motavita'),
    ('Boyacá', 'Muzo'),
    ('Boyacá', 'Nobsa'),
    ('Boyacá', 'Nuevo Colón'),
    ('Boyacá', 'Oicatá'),
    ('Boyacá', 'Otanche'),
    ('Boyacá', 'Pachavita'),
    ('Boyacá', 'Paipa'),
    ('Boyacá', 'Pajarito'),
    ('Boyacá', 'Pauna'),
    ('Boyacá', 'Paz De Rio'),
    ('Boyacá', 'Pesca'),
    ('Boyacá', 'Pisva'),
    ('Boyacá', 'Puerto Boyacá'),
    ('Boyacá', 'Páez'),
    ('Boyacá', 'Quípama'),
    ('Boyacá', 'Ramiriquí'),
    ('Boyacá', 'Rondón'),
    ('Boyacá', 'Ráquira'),
    ('Boyacá', 'Saboyá'),
    ('Boyacá', 'Samacá'),
    ('Boyacá', 'San Luis De Gaceno'),
    ('Boyacá', 'San Mateo'),
    ('Boyacá', 'San Miguel De Sema'),
    ('Boyacá', 'San Pablo De Borbur'),
    ('Boyacá', 'Santa María (Boyacá)'),
    ('Boyacá', 'Santa Rosa De Viterbo'),
    ('Boyacá', 'Santa Sofía'),
    ('Boyacá', 'Santana'),
    ('Boyacá', 'Sativanorte'),
    ('Boyacá', 'Siachoque'),
    ('Boyacá', 'Socha'),
    ('Boyacá', 'Socotá'),
    ('Boyacá', 'Sogamoso'),
    ('Boyacá', 'Somondoco'),
    ('Boyacá', 'Soracá'),
    ('Boyacá', 'Sotaquirá'),
    ('Boyacá', 'Susacón'),
    ('Boyacá', 'Sutamarchán'),
    ('Boyacá', 'Sutatenza'),
    ('Boyacá', 'Sáchica'),
    ('Boyacá', 'Tasco'),
    ('Boyacá', 'Tenza'),
    ('Boyacá', 'Tibaná'),
    ('Boyacá', 'Tibasosa'),
    ('Boyacá', 'Toca'),
    ('Boyacá', 'Tota'),
    ('Boyacá', 'Tunja'),
    ('Boyacá', 'Turmequé'),
    ('Boyacá', 'Tuta'),
    ('Boyacá', 'Tutazá'),
    ('Boyacá', 'Ventaquemada'),
    ('Boyacá', 'Villa De Leiva'),
    ('Boyacá', 'Zetaquirá'),
    ('Boyacá', 'Úmbita'),
    ('Caldas', 'Aguadas'),
    ('Caldas', 'Anserma'),
    ('Caldas', 'Belalcazar'),
    ('Caldas', 'Chinchina'),
    ('Caldas', 'Filadelfia'),
    ('Caldas', 'La Dorada'),
    ('Caldas', 'Manizales'),
    ('Caldas', 'Manzanares'),
    ('Caldas', 'Marmato'),
    ('Caldas', 'Marquetalia'),
    ('Caldas', 'Marulanda'),
    ('Caldas', 'Neira'),
    ('Caldas', 'Norcasia'),
    ('Caldas', 'Palestina (Caldas)'),
    ('Caldas', 'Pensilvania'),
    ('Caldas', 'Pácora'),
    ('Caldas', 'Riosucio (Caldas)'),
    ('Caldas', 'Salamina (Caldas)'),
    ('Caldas', 'Samaná'),
    ('Caldas', 'Supia'),
    ('Caldas', 'Victoria'),
    ('Caldas', 'Villamaria'),
    ('Caldas', 'Viterbo'),
    ('Caquetá', 'Belén De Los Andaquíes'),
    ('Caquetá', 'Cartagena Del Chairá'),
    ('Caquetá', 'El Doncello'),
    ('Caquetá', 'El Paujil'),
    ('Caquetá', 'Florencia (Caquetá)'),
    ('Caquetá', 'Milán'),
    ('Caquetá', 'Montañita'),
    ('Caquetá', 'Morelia'),
    ('Caquetá', 'Puerto Rico (Caquetá)'),
    ('Caquetá', 'San José Del Fragua'),
    ('Caquetá', 'San Vicente Del Caguán'),
    ('Caquetá', 'Solano'),
    ('Caquetá', 'Valparaíso'),
    ('Casanare', 'Aguazul'),
    ('Casanare', 'Chámeza'),
    ('Casanare', 'Hato Corozal'),
    ('Casanare', 'Mani'),
    ('Casanare', 'Monterrey'),
    ('Casanare', 'Nunchía'),
    ('Casanare', 'Orocué'),
    ('Casanare', 'Paz De Ariporo'),
    ('Casanare', 'Pore'),
    ('Casanare', 'Sabanalarga (Casanare)'),
    ('Casanare', 'San Luis De Palenque'),
    ('Casanare', 'Sácama'),
    ('Casanare', 'Tauramena'),
    ('Casanare', 'Trinidad'),
    ('Casanare', 'Támara'),
    ('Casanare', 'Villanueva (Casanare)'),
    ('Casanare', 'Yopal'),
    ('Cauca', 'Almaguer'),
    ('Cauca', 'Argelia (Cauca)'),
    ('Cauca', 'Balboa (Cauca)'),
    ('Cauca', 'Bolívar (Cauca)'),
    ('Cauca', 'Buenos Aires'),
    ('Cauca', 'Cajibío'),
    ('Cauca', 'Caldono'),
    ('Cauca', 'Caloto'),
    ('Cauca', 'Corinto'),
    ('Cauca', 'El Tambo (Cauca)'),
    ('Cauca', 'Guapi'),
    ('Cauca', 'Inzá'),
    ('Cauca', 'Jambaló'),
    ('Cauca', 'La Sierra'),
    ('Cauca', 'La Vega'),
    ('Cauca', 'López'),
    ('Cauca', 'Mercaderes'),
    ('Cauca', 'Miranda'),
    ('Cauca', 'Morales (Cauca)'),
    ('Cauca', 'Patía (El Bordo)'),
    ('Cauca', 'Piendamó'),
    ('Cauca', 'Popayán'),
    ('Cauca', 'Puerto Tejada'),
    ('Cauca', 'Puracé (Coconuco)'),
    ('Cauca', 'Páez (Belalcázar)'),
    ('Cauca', 'Rosas'),
    ('Cauca', 'San Sebastián'),
    ('Cauca', 'Santa Rosa (Cauca)'),
    ('Cauca', 'Santander De Quilichao'),
    ('Cauca', 'Silvia'),
    ('Cauca', 'Sotará (Paispamba)'),
    ('Cauca', 'Suárez (Cauca)'),
    ('Cauca', 'Timbiquí'),
    ('Cauca', 'Timbío'),
    ('Cauca', 'Toribío'),
    ('Cauca', 'Totoró'),
    ('Cauca', 'Villa Rica'),
    ('Cesar', 'Aguachica'),
    ('Cesar', 'Agustín Codazzi'),
    ('Cesar', 'Astrea'),
    ('Cesar', 'Becerrill'),
    ('Cesar', 'Bosconia'),
    ('Cesar', 'Chimichagua'),
    ('Cesar', 'Chiriguaná'),
    ('Cesar', 'Curumaní'),
    ('Cesar', 'El Copey'),
    ('Cesar', 'El Paso'),
    ('Cesar', 'Gamarra'),
    ('Cesar', 'La Gloria'),
    ('Cesar', 'La Jagua De Ibirico'),
    ('Cesar', 'La Paz (Cesar)'),
    ('Cesar', 'Manaure Balcón Del Cesar'),
    ('Cesar', 'Pailitas'),
    ('Cesar', 'Pelaya'),
    ('Cesar', 'Pueblo Bello'),
    ('Cesar', 'Río De Oro'),
    ('Cesar', 'San Alberto'),
    ('Cesar', 'San Diego'),
    ('Cesar', 'San Martín (Cesar)'),
    ('Cesar', 'Tamalameque'),
    ('Cesar', 'Valledupar'),
    ('Chocó', 'Acandí'),
    ('Chocó', 'Alto Baudó (Pie De Pato)'),
    ('Chocó', 'Atrato (Yuto)'),
    ('Chocó', 'Bagadó'),
    ('Chocó', 'Bahía Solano (Mutis)'),
    ('Chocó', 'Bajo Baudó (Pizarro)'),
    ('Chocó', 'Bojayá (Bellavista)'),
    ('Chocó', 'Carmen Del Darién  (Curbaradó)'),
    ('Chocó', 'Condoto'),
    ('Chocó', 'Cértegui'),
    ('Chocó', 'El Cantón Del San Pablo (Managrú)'),
    ('Chocó', 'El Carmen (Choco)'),
    ('Chocó', 'El Litoral Del San Juán (Docordó)'),
    ('Chocó', 'Istmina'),
    ('Chocó', 'Juradó'),
    ('Chocó', 'Lloró'),
    ('Chocó', 'Medio Atrato (Beté)'),
    ('Chocó', 'Medio Baudó(Boca De Pepé)'),
    ('Chocó', 'Medio San Juan'),
    ('Chocó', 'Nuquí'),
    ('Chocó', 'Nóvita'),
    ('Chocó', 'Quibdó'),
    ('Chocó', 'Rio Iró (Santa Rita)'),
    ('Chocó', 'Rio Quito (Paimadó)'),
    ('Chocó', 'Riosucio (Choco)'),
    ('Chocó', 'San José Del Palmar'),
    ('Chocó', 'Sipí'),
    ('Chocó', 'Tadó'),
    ('Chocó', 'Unguía'),
    ('Chocó', 'Unión Panamericana ( Animas)'),
    ('Cundinamarca', 'Anapoima'),
    ('Cundinamarca', 'Anolaima'),
    ('Cundinamarca', 'Bojacá'),
    ('Cundinamarca', 'Cabrera (Cundinamarca)'),
    ('Cundinamarca', 'Caparrapí'),
    ('Cundinamarca', 'Carmen De Carupa'),
    ('Cundinamarca', 'Chaguaní'),
    ('Cundinamarca', 'Chipaque'),
    ('Cundinamarca', 'Choachí'),
    ('Cundinamarca', 'Chocontá'),
    ('Cundinamarca', 'Chía'),
    ('Cundinamarca', 'Cogua'),
    ('Cundinamarca', 'Cota'),
    ('Cundinamarca', 'Cucunubá'),
    ('Cundinamarca', 'Cáqueza'),
    ('Cundinamarca', 'El Colegio'),
    ('Cundinamarca', 'El Peñón (Cundinamarca)'),
    ('Cundinamarca', 'Facatativá'),
    ('Cundinamarca', 'Funza'),
    ('Cundinamarca', 'Fusagasugá'),
    ('Cundinamarca', 'Fómeque'),
    ('Cundinamarca', 'Fúquene'),
    ('Cundinamarca', 'Gachalá'),
    ('Cundinamarca', 'Gachancipá'),
    ('Cundinamarca', 'Gachetá'),
    ('Cundinamarca', 'Gama'),
    ('Cundinamarca', 'Girardot'),
    ('Cundinamarca', 'Guachetá'),
    ('Cundinamarca', 'Guaduas'),
    ('Cundinamarca', 'Guasca'),
    ('Cundinamarca', 'Guatavita'),
    ('Cundinamarca', 'Guayabal De Síquima'),
    ('Cundinamarca', 'Guayabetal'),
    ('Cundinamarca', 'Gutiérrez'),
    ('Cundinamarca', 'Jerusalén'),
    ('Cundinamarca', 'Junín'),
    ('Cundinamarca', 'La Calera'),
    ('Cundinamarca', 'La Mesa'),
    ('Cundinamarca', 'La Palma'),
    ('Cundinamarca', 'La Peña'),
    ('Cundinamarca', 'La Vega'),
    ('Cundinamarca', 'Lenguazaque'),
    ('Cundinamarca', 'Machetá'),
    ('Cundinamarca', 'Madrid'),
    ('Cundinamarca', 'Manta'),
    ('Cundinamarca', 'Medina'),
    ('Cundinamarca', 'Mosquera (Cundinamarca)'),
    ('Cundinamarca', 'Nariño (Cundinamarca)'),
    ('Cundinamarca', 'Nemocón'),
    ('Cundinamarca', 'Nilo'),
    ('Cundinamarca', 'Nocaima'),
    ('Cundinamarca', 'Pacho'),
    ('Cundinamarca', 'Paime'),
    ('Cundinamarca', 'Pandi'),
    ('Cundinamarca', 'Paratebueno'),
    ('Cundinamarca', 'Pasca'),
    ('Cundinamarca', 'Puerto Salgar'),
    ('Cundinamarca', 'Pulí'),
    ('Cundinamarca', 'Quebradanegra'),
    ('Cundinamarca', 'Quetame'),
    ('Cundinamarca', 'Ricaurte (Cundinamarca)'),
    ('Cundinamarca', 'San Bernardo (Cundinamarca)'),
    ('Cundinamarca', 'San Cayetano (Cundinamarca)'),
    ('Cundinamarca', 'San Francisco (Cundinamarca)'),
    ('Cundinamarca', 'San Juan De Rioseco'),
    ('Cundinamarca', 'Sasaima'),
    ('Cundinamarca', 'Sesquilé'),
    ('Cundinamarca', 'Sibaté'),
    ('Cundinamarca', 'Silvania'),
    ('Cundinamarca', 'Simijaca'),
    ('Cundinamarca', 'Soacha'),
    ('Cundinamarca', 'Sopó'),
    ('Cundinamarca', 'Subachoque'),
    ('Cundinamarca', 'Suesca'),
    ('Cundinamarca', 'Supata'),
    ('Cundinamarca', 'Susa'),
    ('Cundinamarca', 'Tabio'),
    ('Cundinamarca', 'Tausa'),
    ('Cundinamarca', 'Tenjo'),
    ('Cundinamarca', 'Tibacuy'),
    ('Cundinamarca', 'Tibirita'),
    ('Cundinamarca', 'Tocaima'),
    ('Cundinamarca', 'Tocancipá'),
    ('Cundinamarca', 'Ubalá'),
    ('Cundinamarca', 'Ubaque'),
    ('Cundinamarca', 'Ubaté'),
    ('Cundinamarca', 'Venecia (Cundinamarca)'),
    ('Cundinamarca', 'Villagómez'),
    ('Cundinamarca', 'Villapinzón'),
    ('Cundinamarca', 'Villeta'),
    ('Cundinamarca', 'Viotá'),
    ('Cundinamarca', 'Yacopí'),
    ('Cundinamarca', 'Zipaquirá'),
    ('Cundinamarca', 'Útica'),
    ('Córdoba', 'Ayapel'),
    ('Córdoba', 'Buenavista (Córdoba)'),
    ('Córdoba', 'Canalete'),
    ('Córdoba', 'Cereté'),
    ('Córdoba', 'Chima (Córdoba)'),
    ('Córdoba', 'Chinú'),
    ('Córdoba', 'Ciénaga De Oro'),
    ('Córdoba', 'Cotorra'),
    ('Córdoba', 'La Apartada'),
    ('Córdoba', 'Lorica'),
    ('Córdoba', 'Momil'),
    ('Córdoba', 'Montelíbano'),
    ('Córdoba', 'Montería'),
    ('Córdoba', 'Planeta Rica'),
    ('Córdoba', 'Pueblo Nuevo'),
    ('Córdoba', 'Puerto Escondido'),
    ('Córdoba', 'Puerto Libertador'),
    ('Córdoba', 'Sahagún'),
    ('Córdoba', 'San Andrés De Sotavento'),
    ('Córdoba', 'San Antero'),
    ('Córdoba', 'San Bernardo Del Viento'),
    ('Córdoba', 'San Carlos (Córdoba)'),
    ('Córdoba', 'San Jose De Ure'),
    ('Córdoba', 'San Pelayo'),
    ('Córdoba', 'Tierralta'),
    ('Córdoba', 'Valencia'),
    ('Guainía', 'Barranco Mina'),
    ('Guainía', 'Inírida'),
    ('Guainía', 'Mapiripana'),
    ('Guaviare', 'El Retorno'),
    ('Guaviare', 'San José Del Guaviare'),
    ('Huila', 'Acevedo'),
    ('Huila', 'Agrado'),
    ('Huila', 'Aipe'),
    ('Huila', 'Algeciras'),
    ('Huila', 'Altamira'),
    ('Huila', 'Baraya'),
    ('Huila', 'Campoalegre'),
    ('Huila', 'Colombia'),
    ('Huila', 'Elías'),
    ('Huila', 'Garzón'),
    ('Huila', 'Gigante'),
    ('Huila', 'Guadalupe (Huila)'),
    ('Huila', 'Hobo'),
    ('Huila', 'Isnos'),
    ('Huila', 'La Argentina'),
    ('Huila', 'La Plata'),
    ('Huila', 'Neiva'),
    ('Huila', 'Nátaga'),
    ('Huila', 'Oporapa'),
    ('Huila', 'Paicol'),
    ('Huila', 'Palermo'),
    ('Huila', 'Palestina (Huila)'),
    ('Huila', 'Pital'),
    ('Huila', 'Pitalito'),
    ('Huila', 'Rivera'),
    ('Huila', 'Saladoblanco'),
    ('Huila', 'San Agustín'),
    ('Huila', 'Santa María (Huila)'),
    ('Huila', 'Suaza'),
    ('Huila', 'Tarqui'),
    ('Huila', 'Tello'),
    ('Huila', 'Teruel'),
    ('Huila', 'Tesalia'),
    ('Huila', 'Villavieja'),
    ('Huila', 'Yaguará'),
    ('Huila', 'Íquira'),
    ('La Guajira', 'Albania (La guajira)'),
    ('La Guajira', 'Barrancas'),
    ('La Guajira', 'Dibulla'),
    ('La Guajira', 'Distracción'),
    ('La Guajira', 'Fonseca'),
    ('La Guajira', 'Hato Nuevo'),
    ('La Guajira', 'La Jagua Del Pilar'),
    ('La Guajira', 'Maicao'),
    ('La Guajira', 'Manaure'),
    ('La Guajira', 'Riohacha'),
    ('La Guajira', 'San Juan Del Cesar'),
    ('La Guajira', 'Uribia'),
    ('La Guajira', 'Urumita'),
    ('La Guajira', 'Villanueva (La guajira)'),
    ('Magdalena', 'Algarrobo'),
    ('Magdalena', 'Aracataca'),
    ('Magdalena', 'Ariguaní (El Dificil)'),
    ('Magdalena', 'Ciénaga'),
    ('Magdalena', 'El Banco'),
    ('Magdalena', 'El Piñón'),
    ('Magdalena', 'El Retén'),
    ('Magdalena', 'Fundación'),
    ('Magdalena', 'Nueva Granada'),
    ('Magdalena', 'Pivijai'),
    ('Magdalena', 'Plato'),
    ('Magdalena', 'Puebloviejo'),
    ('Magdalena', 'Remolino'),
    ('Magdalena', 'Sabanas De San Ángel'),
    ('Magdalena', 'Salamina (Magdalena)'),
    ('Magdalena', 'San Sebastián De Buenavista'),
    ('Magdalena', 'San Zenón'),
    ('Magdalena', 'Santa Ana'),
    ('Magdalena', 'Santa Bárbara De Pinto'),
    ('Magdalena', 'Santa Marta'),
    ('Magdalena', 'Sitionuevo'),
    ('Magdalena', 'Tenerife'),
    ('Magdalena', 'Zona Bananera'),
    ('Meta', 'Acacías'),
    ('Meta', 'Barranca De Upía'),
    ('Meta', 'Cabuyaro'),
    ('Meta', 'Castilla La Nueva'),
    ('Meta', 'Cubarral'),
    ('Meta', 'Cumaral'),
    ('Meta', 'El Calvario'),
    ('Meta', 'El Castillo'),
    ('Meta', 'El Dorado'),
    ('Meta', 'Fuente De Oro'),
    ('Meta', 'Granada (Meta)'),
    ('Meta', 'Guamal (Meta)'),
    ('Meta', 'La Macarena'),
    ('Meta', 'Lejanías'),
    ('Meta', 'Mapiripán'),
    ('Meta', 'Mesetas'),
    ('Meta', 'Puerto Concordia'),
    ('Meta', 'Puerto Gaitán'),
    ('Meta', 'Puerto Lleras'),
    ('Meta', 'Puerto López'),
    ('Meta', 'Puerto Rico (Meta)'),
    ('Meta', 'Restrepo (Meta)'),
    ('Meta', 'San Carlos De Guaroa'),
    ('Meta', 'San Juan De Arama'),
    ('Meta', 'San Martín (Meta)'),
    ('Meta', 'Uribe'),
    ('Meta', 'Villavicencio'),
    ('Meta', 'Vistahermosa'),
    ('Nariño', 'Aldana'),
    ('Nariño', 'Arboleda (Berruecos)'),
    ('Nariño', 'Barbacoas'),
    ('Nariño', 'Buesaco'),
    ('Nariño', 'Chachaguí'),
    ('Nariño', 'Colón (Génova)'),
    ('Nariño', 'Consacá'),
    ('Nariño', 'Contadero'),
    ('Nariño', 'Cuaspud (Carlosama)'),
    ('Nariño', 'Cumbal'),
    ('Nariño', 'Cumbitara'),
    ('Nariño', 'El Charco'),
    ('Nariño', 'El Peñol'),
    ('Nariño', 'El Rosario'),
    ('Nariño', 'El Tablón'),
    ('Nariño', 'El Tambo (Nariño)'),
    ('Nariño', 'Francisco Pizarro (Salahonda)'),
    ('Nariño', 'Funes'),
    ('Nariño', 'Gualmatán'),
    ('Nariño', 'Imués'),
    ('Nariño', 'Ipiales'),
    ('Nariño', 'La Cruz'),
    ('Nariño', 'La Llanada'),
    ('Nariño', 'La Unión (Nariño)'),
    ('Nariño', 'Leiva'),
    ('Nariño', 'Linares'),
    ('Nariño', 'Los Andes (Sotomayor)'),
    ('Nariño', 'Magüí (Payán)'),
    ('Nariño', 'Mallama (Piedrancha)'),
    ('Nariño', 'Mosquera (Nariño)'),
    ('Nariño', 'Nariño (Nariño)'),
    ('Nariño', 'Pasto'),
    ('Nariño', 'Policarpa'),
    ('Nariño', 'Potosí'),
    ('Nariño', 'Puerres'),
    ('Nariño', 'Pupiales'),
    ('Nariño', 'Ricaurte (Nariño)'),
    ('Nariño', 'Roberto Payán (San José)'),
    ('Nariño', 'Samaniego'),
    ('Nariño', 'San Bernardo (Nariño)'),
    ('Nariño', 'Sandoná'),
    ('Nariño', 'Santa Cruz (Guachavés)'),
    ('Nariño', 'Sapuyes'),
    ('Nariño', 'Taminango'),
    ('Nariño', 'Tangua'),
    ('Nariño', 'Tumaco'),
    ('Nariño', 'Túquerres'),
    ('Norte de Santander', 'Arboledas'),
    ('Norte de Santander', 'Bochalema'),
    ('Norte de Santander', 'Chinácota'),
    ('Norte de Santander', 'Chitagá'),
    ('Norte de Santander', 'Convención'),
    ('Norte de Santander', 'Cucutilla'),
    ('Norte de Santander', 'Cáchira'),
    ('Norte de Santander', 'Cácota'),
    ('Norte de Santander', 'Cúcuta'),
    ('Norte de Santander', 'Durania'),
    ('Norte de Santander', 'El Carmen (Norte de Santander)'),
    ('Norte de Santander', 'El Tarra'),
    ('Norte de Santander', 'El Zulia'),
    ('Norte de Santander', 'Gramalote'),
    ('Norte de Santander', 'Hacarí'),
    ('Norte de Santander', 'Herrán'),
    ('Norte de Santander', 'La Esperanza'),
    ('Norte de Santander', 'La Playa'),
    ('Norte de Santander', 'Labateca'),
    ('Norte de Santander', 'Lourdes'),
    ('Norte de Santander', 'Mutiscua'),
    ('Norte de Santander', 'Ocaña'),
    ('Norte de Santander', 'Pamplona'),
    ('Norte de Santander', 'Pamplonita'),
    ('Norte de Santander', 'Puerto Santander'),
    ('Norte de Santander', 'Ragonvalia'),
    ('Norte de Santander', 'Salazar'),
    ('Norte de Santander', 'San Calixto'),
    ('Norte de Santander', 'San Cayetano (Norte de Santander)'),
    ('Norte de Santander', 'Santiago (Norte de Santander)'),
    ('Norte de Santander', 'Sardinata'),
    ('Norte de Santander', 'Silos'),
    ('Norte de Santander', 'Teorama'),
    ('Norte de Santander', 'Tibú'),
    ('Norte de Santander', 'Toledo (Norte de Santander)'),
    ('Norte de Santander', 'Villa Caro'),
    ('Norte de Santander', 'Villa Del Rosario'),
    ('Norte de Santander', 'Ábrego'),
    ('Putumayo', 'Colón'),
    ('Putumayo', 'Mocoa'),
    ('Putumayo', 'Orito'),
    ('Putumayo', 'Puerto Asís'),
    ('Putumayo', 'Puerto Caicedo'),
    ('Putumayo', 'Puerto Guzmán'),
    ('Putumayo', 'Puerto Leguízamo'),
    ('Putumayo', 'San Francisco (Putumayo)'),
    ('Putumayo', 'San Miguel (La Dorada)'),
    ('Putumayo', 'Santiago (Putumayo)'),
    ('Putumayo', 'Sibundoy'),
    ('Putumayo', 'Valle Del Guamuez (La Hormiga)'),
    ('Putumayo', 'Villagarzón'),
    ('Quindío', 'Armenia (Quindío)'),
    ('Quindío', 'Calarcá'),
    ('Quindío', 'Circasia'),
    ('Quindío', 'Génova'),
    ('Quindío', 'La Tebaida'),
    ('Quindío', 'Pijao'),
    ('Quindío', 'Salento'),
    ('RIsaralda', 'Apía'),
    ('RIsaralda', 'Belén De Umbría'),
    ('RIsaralda', 'Dosquebradas'),
    ('RIsaralda', 'Guática'),
    ('RIsaralda', 'La Virginia'),
    ('RIsaralda', 'Marsella'),
    ('RIsaralda', 'Mistrató'),
    ('RIsaralda', 'Pereira'),
    ('RIsaralda', 'Pueblo Rico'),
    ('RIsaralda', 'Quinchía'),
    ('RIsaralda', 'Santa Rosa De Cabal'),
    ('RIsaralda', 'Santuario (Risaralda)'),
    ('Santander', 'Albania (Santander)'),
    ('Santander', 'Aratoca'),
    ('Santander', 'Barichara'),
    ('Santander', 'Barrancabermeja'),
    ('Santander', 'Betulia (Santander)'),
    ('Santander', 'Bolivar (Santander)'),
    ('Santander', 'Bucaramanga'),
    ('Santander', 'Cabrera (Santander)'),
    ('Santander', 'California'),
    ('Santander', 'Capitanejo'),
    ('Santander', 'Carcasí'),
    ('Santander', 'Cepitá'),
    ('Santander', 'Cerrito'),
    ('Santander', 'Charalá'),
    ('Santander', 'Charta'),
    ('Santander', 'Chima (Santander)'),
    ('Santander', 'Cimitarra'),
    ('Santander', 'Concepción (Santander)'),
    ('Santander', 'Confines'),
    ('Santander', 'Contratación'),
    ('Santander', 'Coromoro'),
    ('Santander', 'Curití'),
    ('Santander', 'El Carmen (Santander)'),
    ('Santander', 'El Playón'),
    ('Santander', 'Encino'),
    ('Santander', 'Floridablanca'),
    ('Santander', 'Girón'),
    ('Santander', 'Guaca'),
    ('Santander', 'Guadalupe (Santander)'),
    ('Santander', 'Guavatá'),
    ('Santander', 'Gámbita'),
    ('Santander', 'Jesús María'),
    ('Santander', 'Landázuri'),
    ('Santander', 'Lebrija'),
    ('Santander', 'Los Santos'),
    ('Santander', 'Macaravita'),
    ('Santander', 'Matanza'),
    ('Santander', 'Mogotes'),
    ('Santander', 'Molagavita'),
    ('Santander', 'Málaga'),
    ('Santander', 'Ocamonte'),
    ('Santander', 'Oiba'),
    ('Santander', 'Onzaga'),
    ('Santander', 'Palmar'),
    ('Santander', 'Piedecuesta'),
    ('Santander', 'Pinchote'),
    ('Santander', 'Puente Nacional'),
    ('Santander', 'Puerto Parra'),
    ('Santander', 'Puerto Wilches'),
    ('Santander', 'Páramo'),
    ('Santander', 'Rionegro (Santander)'),
    ('Santander', 'Sabana De Torres'),
    ('Santander', 'San Andrés (Santander)'),
    ('Santander', 'San Benito'),
    ('Santander', 'San Gil'),
    ('Santander', 'San Joaquín'),
    ('Santander', 'San Vicente De Chucurí'),
    ('Santander', 'Santa Bárbara (Santander)'),
    ('Santander', 'Simacota'),
    ('Santander', 'Socorro'),
    ('Santander', 'Suaita'),
    ('Santander', 'Sucre (Santander)'),
    ('Santander', 'Suratá'),
    ('Santander', 'Tona'),
    ('Santander', 'Valle De San José'),
    ('Santander', 'Vetas'),
    ('Santander', 'Vélez'),
    ('Santander', 'Zapatoca'),
    ('Sucre', 'Buenavista (Sucre)'),
    ('Sucre', 'Caimito'),
    ('Sucre', 'Chalán'),
    ('Sucre', 'Colosó'),
    ('Sucre', 'Corozal'),
    ('Sucre', 'Galeras'),
    ('Sucre', 'Guaranda'),
    ('Sucre', 'Los Palmitos'),
    ('Sucre', 'Majagual'),
    ('Sucre', 'Morroa'),
    ('Sucre', 'Ovejas'),
    ('Sucre', 'Sampués'),
    ('Sucre', 'San Benito Abad'),
    ('Sucre', 'San Juan De Betulia (Betulia)'),
    ('Sucre', 'San Marcos'),
    ('Sucre', 'San Onofre'),
    ('Sucre', 'San Pedro (Sucre)'),
    ('Sucre', 'Sincelejo'),
    ('Sucre', 'Sincé'),
    ('Sucre', 'Sucre (Sucre)'),
    ('Sucre', 'Tolú'),
    ('Sucre', 'Tolú Viejo'),
    ('Tolima', 'Alpujarra'),
    ('Tolima', 'Alvarado'),
    ('Tolima', 'Ambalema'),
    ('Tolima', 'Anzoátegui'),
    ('Tolima', 'Armero (Guayabal)'),
    ('Tolima', 'Ataco'),
    ('Tolima', 'Cajamarca'),
    ('Tolima', 'Carmen De Apicalá'),
    ('Tolima', 'Chaparral'),
    ('Tolima', 'Coyaima'),
    ('Tolima', 'Cunday'),
    ('Tolima', 'Dolores'),
    ('Tolima', 'Espinal'),
    ('Tolima', 'Falan'),
    ('Tolima', 'Flandes'),
    ('Tolima', 'Fresno'),
    ('Tolima', 'Guamo'),
    ('Tolima', 'Honda'),
    ('Tolima', 'Ibagué'),
    ('Tolima', 'Icononzo'),
    ('Tolima', 'Lérida'),
    ('Tolima', 'Líbano'),
    ('Tolima', 'Mariquita'),
    ('Tolima', 'Melgar'),
    ('Tolima', 'Murillo'),
    ('Tolima', 'Natagaima'),
    ('Tolima', 'Ortega'),
    ('Tolima', 'Piedras'),
    ('Tolima', 'Planadas'),
    ('Tolima', 'Prado'),
    ('Tolima', 'Purificación'),
    ('Tolima', 'Rioblanco'),
    ('Tolima', 'Roncesvalles'),
    ('Tolima', 'Rovira'),
    ('Tolima', 'Saldaña'),
    ('Tolima', 'San Antonio'),
    ('Tolima', 'San Luis (Tolima)'),
    ('Tolima', 'Santa Isabel'),
    ('Tolima', 'Suárez (Tolima)'),
    ('Tolima', 'Valle De San Juan'),
    ('Tolima', 'Venadillo'),
    ('Tolima', 'Villahermosa'),
    ('Tolima', 'Villarrica'),
    ('Valle del Cauca', 'Alcalá'),
    ('Valle del Cauca', 'Andalucía'),
    ('Valle del Cauca', 'Ansermanuevo'),
    ('Valle del Cauca', 'Argelia (Valle del cauca)'),
    ('Valle del Cauca', 'Bolívar (Valle del cauca)'),
    ('Valle del Cauca', 'Buenaventura'),
    ('Valle del Cauca', 'Buga'),
    ('Valle del Cauca', 'Bugalagrande'),
    ('Valle del Cauca', 'Caicedonia'),
    ('Valle del Cauca', 'Cali'),
    ('Valle del Cauca', 'Candelaria (Valle del cauca)'),
    ('Valle del Cauca', 'Cartago'),
    ('Valle del Cauca', 'Dagua'),
    ('Valle del Cauca', 'El Cerrito'),
    ('Valle del Cauca', 'El Dovio'),
    ('Valle del Cauca', 'El Águila'),
    ('Valle del Cauca', 'Florida'),
    ('Valle del Cauca', 'Ginebra'),
    ('Valle del Cauca', 'Guacarí'),
    ('Valle del Cauca', 'Jamundí'),
    ('Valle del Cauca', 'La Cumbre'),
    ('Valle del Cauca', 'La Unión (Valle del cauca)'),
    ('Valle del Cauca', 'La Victoria (Valle del cauca)'),
    ('Valle del Cauca', 'Obando'),
    ('Valle del Cauca', 'Palmira'),
    ('Valle del Cauca', 'Riofrío'),
    ('Valle del Cauca', 'Roldanillo'),
    ('Valle del Cauca', 'San Pedro (Valle del cauca)'),
    ('Valle del Cauca', 'Sevilla'),
    ('Valle del Cauca', 'Toro'),
    ('Valle del Cauca', 'Tuluá'),
    ('Valle del Cauca', 'Versalles'),
    ('Valle del Cauca', 'Vijes'),
    ('Valle del Cauca', 'Yotoco'),
    ('Valle del Cauca', 'Zarzal'),
    ('Vaupes', 'Mitú'),
    ('Vaupes', 'Taraira'),
    ('Vaupes', 'Yavaraté  (Cor. Departamental)'),
    ('Vichada', 'Cumaribo'),
    ('Vichada', 'La Primavera'),
    ('Vichada', 'Puerto Carreño'),
    ('Vichada', 'Santa Rosalía'),
)
